name: CI/CD para AWS EKS
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rogeriofontes/selectgearmotors-bff-api:v8

      - name: Configure kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name selectgearmotors-eks-cluster

      - name: Create Kubernetes Secret YAML
        run: |
          cat <<EOF > infra/k8s/secrets.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: selectgearmotors-bff-api-secrets
            namespace: selectgearmotors-ns
          type: Opaque
          stringData:
            API_PORT: "${{ secrets.API_PORT }}"
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            AWS_REGION: "${{ secrets.AWS_REGION }}"
            CLIENT_TYPES_URL: "${{ secrets.CLIENT_TYPES_URL }}"
            CLIENTS_LEGAL_URL: "${{ secrets.CLIENTS_LEGAL_URL }}"
            CLIENTS_MEDIA_URL: "${{ secrets.CLIENTS_MEDIA_URL }}"
            CLIENTS_PHYSICAL_URL: "${{ secrets.CLIENTS_PHYSICAL_URL }}"
            CLIENTS_URL: "${{ secrets.CLIENTS_URL }}"
            COMPANIES_URL: "${{ secrets.COMPANIES_URL }}"
            COMPANY_CAR_SELLERS_URL: "${{ secrets.COMPANY_CAR_SELLERS_URL }}"
            COMPANY_MEDIA_URL: "${{ secrets.COMPANY_MEDIA_URL }}"
            COMPANY_TYPES_URL: "${{ secrets.COMPANY_TYPES_URL }}"
            SECURITY_JWT_SECRET_KEY: "${{ secrets.SECURITY_JWT_SECRET_KEY }}"
            TRANSACTION_TYPES_URL: "${{ secrets.TRANSACTION_TYPES_URL }}"
            TRANSACTIONS_URL: "${{ secrets.TRANSACTIONS_URL }}"
            VEHICLE_TYPES_URL: "${{ secrets.VEHICLE_TYPES_URL }}"
            VEHICLES_BRANDS_URL: "${{ secrets.VEHICLES_BRANDS_URL }}"
            VEHICLES_CATEGORIES_URL: "${{ secrets.VEHICLES_CATEGORIES_URL }}"
            VEHICLES_MODELS_URL: "${{ secrets.VEHICLES_MODELS_URL }}"
            VEHICLES_URL: "${{ secrets.VEHICLES_URL }}"
            SWAGGER_API_URL: "${{ secrets.SWAGGER_API_URL }}"
            ZIPKIN_URL: "${{ secrets.ZIPKIN_URL }}"
          EOF

      - name: Apply ConfigMap and Secrets
        run: |
          kubectl apply -f infra/k8s/configmap.yaml
          kubectl apply -f infra/k8s/secrets.yaml

      - name: Apply Kubernetes Service
        run: |
          kubectl apply -f infra/k8s/service.yaml -n selectgearmotors-ns

      - name: Deploy API to EKS Cluster
        run: |
          kubectl apply -f infra/k8s/deployment.yaml -n selectgearmotors-ns
